systers/malaria-app-android

res/layout/tripindicator_layout.xml, src/com/peacecorps/malaria/TripIndicatorFragmentActivity.java, src/com/peacecorps/malaria/TripIndicatorPackingActivity.java
Autocomplete is now provided for the location field, which uses the previously visited locations as possible completions.
Before:
After:
=> Autocompletion for location field

res/layout/trip_indicator_packing_dialog.xml, src/com/peacecorps/malaria/TripIndicatorFragmentActivity.java, src/com/peacecorps/malaria/TripIndicatorPackingActivity.java
Reverts systers/malaria-app-android#20
=> Revert "Correct no. drugs calculated for trip on TripIndicatorFragmentActivity"

src/com/peacecorps/malaria/DatabaseSQLiteHelper.java, src/com/peacecorps/malaria/FirstAnalyticFragment.java
New PR corresponding to PR #12 with merge conflicts resolved.
=> Fixed bug in the medicine last taken function

res/layout/trip_indicator_packing_dialog.xml, res/layout/tripindicator_layout.xml, src/com/peacecorps/malaria/TripIndicatorFragmentActivity.java, src/com/peacecorps/malaria/TripIndicatorPackingActivity.java
This is a combined PR for #13 and #20
=> Correct no. of drugs | Prompt user to enter all fields

malaria-app-android/src/main/java/com/peacecorps/malaria/fragment/ThirdAnalyticFragment.java
#111 
@chhavip @MeepyMay 
App crash due to index out of bound solved.
=> Bug solved #111

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/RemainderToneActivity.java
Fixed #109 
App was crashing is user enters a empty or invalid file path. The problem is solved now.
=> Bug removed #109

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/RapidFireGame.java, malaria-app-android/src/main/res/layout/rapid_fire.xml
Once the user chooses an option in the game , all other options will be disabled.
=> RapidFireGame Bug Fixed

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorFragmentActivity.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorPackingActivity.java
Solved issue #135 
@chhavip please review the PR.
=> PlanMyTrip bugs solved.

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/MedicineStore.java
Solved issue #138 
@yatna please review the PR.
=> MedicineStore order bug fixed.

malaria-app-android/src/main/AndroidManifest.xml, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/PeaceCorpsPolicyFragmentActivity.java
Issue #149 fixed . Now the texttospeech stops when the back button is pressed after orientation change and also when the user navigates to home screen.
@yatna @chhavip Kindly review the P.R
=> Bug in PeaceCorpsPolicyFragmentActivity fixed

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/UserMedicineSettingsFragmentActivity.java, malaria-app-android/src/main/res/layout/fragment_user_medicine_settings.xml
Solved issue #132 
@chhavip @yatna 
please review the PR.
=> Done button in UserMedicineSettingsFragmentActivity faded.

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/RapidFireGame.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorFragmentActivity.java, malaria-app-android/src/main/res/values/strings.xml
1) The timer in the quiz now pauses when the dialog box appears and resumes on cancel.(#126)
2)The departure date cannot be before the current date.(#130)
=> Solved bug related to quiztimer and departure date

malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
Fixed the issue related to app crash #134
=> Fixed the issue of appcrash in DayFragmentActivty

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/RapidFireGame.java
#146 #147 Here I have solved 3 problems -
1. App Crash on orientation change
This was because timer was not cancelled on orientation change and when this timer finishes it can't find its context activity.
I have cancelled the timer in onDestroy() 
2. Dialog closes on orientation change
I have attached dialog with WindowManager inside doKeepDialog(). This way dialog is never destroyed if orientation changes.
3. All data lost and game restarts on orientation change
I have saved the current ques no., timer time (to keep a account of this, introduced millisLeft which gets updated in onTick()), and game score in saveInstanceState and then used them in initialize state. I have checked in line 77 if initializing game is for starting the game or due to orientation change and called ask question …
=> Fix #146 #147 Orientation Bugs in RapidFireGame

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/UserProfile.java
Fixes issue #186
@yatna @chhavip 
please review the PR.
=> User profile age bug solved.

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/DayFragmentActivity.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorFragmentActivity.java, malaria-app-android/src/main/res/values/integers.xml, malaria-app-android/src/main/res/xml/appwidget_info.xml, malaria-app-android/src/main/res/xml/statusappwidget_info.xml
Solves issue #192 
@yatna @chhavip 
Please review the PR.
=> Widgets updated instantly.

malaria-app-android/src/main/AndroidManifest.xml
Fixed layout distortion in TripIndicatorFragmentActivity
=> Fixed work done in #29 

malaria-app-android/src/main/java/com/peacecorps/malaria/adapter/DrugArrayAdapter.java, malaria-app-android/src/main/res/values/strings.xml
Fixes #54 : Added a ClickableSpan in DrugArrayAdapter which takes directly to the DrugSite
**Screen shot for the change**
@chhavip @anubhakushwaha @yatna please review this PR. Thanks :)
=> Fixes #54:Added a ClickableSpan in DrugArrayAdapter Activity

malaria-app-android/src/main/res/layout/badge_room_dialog.xml, malaria-app-android/src/main/res/layout/day_dialog.xml, malaria-app-android/src/main/res/layout/effectiveness_fragment.xml, malaria-app-android/src/main/res/layout/fragment_day.xml, malaria-app-android/src/main/res/layout/fragment_first_analytic_screen.xml, malaria-app-android/src/main/res/layout/fragment_home_screen.xml, malaria-app-android/src/main/res/layout/fragment_third_analytic_screen.xml, malaria-app-android/src/main/res/layout/info_hub_screen.xml, malaria-app-android/src/main/res/layout/resetdata_dialog.xml, malaria-app-android/src/main/res/layout/side_effects_percentage_fragment.xml, malaria-app-android/src/main/res/layout/statusappwidget.xml, malaria-app-android/src/main/res/layout/trip_drug_item.xml, malaria-app-android/src/main/res/layout/trip_indicator_packing_dialog.xml, malaria-app-android/src/main/res/layout/tripindicator_layout.xml, malaria-app-android/src/main/res/values/strings.xml
=> Added contentDescription for Accesiblity settings

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/MedicineStore.java, malaria-app-android/src/main/res/values/strings.xml
Fixes #197 along with point number 2 in issue #216 
@chhavip @yatna @anubhakushwaha Please review this PR.Thanks :)
=> Fixes #197:App crashes in MedicineStore Activity

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/DayFragmentActivity.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorFragmentActivity.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/UserMedicineSettingsFragmentActivity.java, malaria-app-android/src/main/java/com/peacecorps/malaria/fragment/FirstAnalyticFragment.java, malaria-app-android/src/main/java/com/peacecorps/malaria/fragment/HomeScreenFragment.java
Solves issue #188 
@chhavip @anubhakushwaha @yatna
please review.
=> Memory leak fixed.

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/TripIndicatorPackingActivity.java, malaria-app-android/src/main/res/layout/trip_indicator_packing_dialog.xml
Fixes issue #208 
**GIF for the changes I have made** 
@chhavip @yatna @anubhakushwaha Please review this PR. Thanks :)
=> Fixes #208:Scrolling issue in TripIndicatorPackingDialog in Landscape mode

malaria-app-android/src/main/java/com/peacecorps/malaria/activities/MedicineStore.java, malaria-app-android/src/main/java/com/peacecorps/malaria/activities/UserProfile.java, malaria-app-android/src/main/res/values/strings.xml
Fixes issue #216
@yatna @chhavip @anubhakushwaha 
please review the PR.
=> Fixes #216 : Age limit fixed.

README.md
Updated README.md by adding general guidelines to be followed while making contributions to malaria-app-android.
=> Guidelines for contributors

malaria-app-android/src/main/res/layout/user_profile.xml
Fixes issue #200 
@anubhakushwaha 
Please review.
=> Made username EditText single line.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
In continuity with PR #179 
@anubhakushwaha 
please review.
=> Add templates for Issue and PullRequest.

.gitignore
Adresses #190 
@yatna @chhavip please review and merge it. :)
=> Gitignore fixed

build.gradle, gradle/wrapper/gradle-wrapper.properties, malaria-app-android/build.gradle
=> latest android version as well as android studio version supported

.travis.yml, README.md
Fixes issue #286 
* Added travis.yml file & status image 
* I haven't added scripts for instrumentation tests. If it's required, I'll update the Pull request.
=> added travis.yml & build status badge

.travis.yml, generate-apk.sh
Fixes issue #290 
Automate the apk generation process
=> Apk auto build
